/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferreira
 */
public class ConexaoBD extends javax.swing.JFrame {

    /**
     * Creates new form ConexaoBD
     */
    public ConexaoBD() {
        
        initComponents();
        //ImageIcon img = new ImageIcon(getClass().getResource("/imagens/download.png"));
        ImageIcon img = new ImageIcon(getClass().getResource("/imagens/download.png"));
        
        Image image = img.getImage();
        //largura e altura
        Image newimg = image.getScaledInstance(150, 70, java.awt.Image.SCALE_SMOOTH);  
        imagem.setIcon(new ImageIcon(newimg));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btSel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btLimp = new javax.swing.JButton();
        btAlt = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXERCÍCIO");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);
        getContentPane().add(txtId);
        txtId.setBounds(160, 130, 46, 20);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(160, 160, 258, 20);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(160, 200, 207, 20);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 130, 20, 14);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 40, 14);

        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 200, 50, 14);

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btInserir);
        btInserir.setBounds(50, 240, 63, 23);

        btSel.setText("Selecionar");
        btSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelActionPerformed(evt);
            }
        });
        getContentPane().add(btSel);
        btSel.setBounds(130, 240, 81, 23);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 280, 452, 153);

        btLimp.setText("Limpar");
        btLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpActionPerformed(evt);
            }
        });
        getContentPane().add(btLimp);
        btLimp.setBounds(410, 240, 63, 23);

        btAlt.setText("Alterar");
        btAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltActionPerformed(evt);
            }
        });
        getContentPane().add(btAlt);
        btAlt.setBounds(230, 240, 65, 23);

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 240, 63, 23);
        getContentPane().add(imagem);
        imagem.setBounds(130, 20, 230, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed

        try {

            Class.forName("com.mysql.jdbc.Driver");
            // 

            Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/aulas", "root", "");

            Statement stm = conn.createStatement();

            String sql = "insert into pessoas (nome, email) values ("
                    +  "'" + txtNome.getText()
                    + "', '" + txtEmail.getText() + "') ";

            
            
            int num = stm.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            
            ResultSet rr = stm.getGeneratedKeys();
            System.out.println(rr.getMetaData().getColumnName(1));
            if (rr.next()){
                System.out.println("I: " + rr.getInt(1));
            }
            
            if (num > 0) {
                JOptionPane.showMessageDialog(null, "Objeto inserido com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível inserir o objeto.", "", JOptionPane.ERROR_MESSAGE);
            }

            stm.close();
            conn.close();
            
        } catch (Exception e) {

            System.out.println("ERRO: " + e.getMessage());

        }


    }//GEN-LAST:event_btInserirActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        // TODO add your handling code here:

        String novo = txtNome.getText().toUpperCase();
        txtNome.setText(novo);

    }//GEN-LAST:event_txtNomeFocusLost

    private void btAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltActionPerformed
        // TODO add your handling code here:

        try {

            Class.forName("com.mysql.jdbc.Driver");
            //

            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/aulas", "root", "");

            String sql = "update pessoas set nome = ?, email = ? where id = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txtNome.getText());
            ps.setString(2, txtEmail.getText());
            ps.setInt(3, Integer.valueOf(txtId.getText()));

            int num = ps.executeUpdate();
            if (num > 0) {
                JOptionPane.showMessageDialog(null, "Objeto alterado com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível alterar o objeto.", "", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {

            System.out.println("ERRO: " + e.getMessage());

        }

    }//GEN-LAST:event_btAltActionPerformed

    private void btSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelActionPerformed
        // TODO add your handling code here:

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/aulas", "root", "");
            Statement stm = conn.createStatement();

            // comando SQL para selecionar todas as colunas da tabela pessoas
            // onde o nome possua a palavra FERREIRA em qualquer parte
            String sql = "select * from pessoas";
            ResultSet rs = stm.executeQuery(sql); // executa o comando SQL

            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            while (rs.next()) {

                String[] linha = new String[]{rs.getString("id"),
                    rs.getString("nome"), rs.getString("email")};
                modelo.addRow(linha);  // adiciona a linha na JTable

            }

            rs.close();
            stm.close();
            conn.close();

        } catch (Exception e) {

            System.out.println("ERRO: " + e.getMessage());

        }

    }//GEN-LAST:event_btSelActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        DefaultTableModel modelo = (DefaultTableModel)tabela.getModel();

        txtId.setText((String)modelo.getValueAt(tabela.getSelectedRow(), 0));
        txtNome.setText((String)modelo.getValueAt(tabela.getSelectedRow(), 1));
        txtEmail.setText((String)modelo.getValueAt(tabela.getSelectedRow(), 2));
    }//GEN-LAST:event_tabelaMouseClicked

    private void btLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtNome.setText("");
        txtEmail.setText("");

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }//GEN-LAST:event_btLimpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexaoBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexaoBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlt;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimp;
    private javax.swing.JButton btSel;
    private javax.swing.JLabel imagem;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
